# Generated by Django 4.2.2 on 2023-06-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_profile_phone_number_alter_pythoncourse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythoncourse',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
