# Generated by Django 4.2.2 on 2023-06-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_profile_video_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='video_files',
        ),
        migrations.AddField(
            model_name='pythoncourse',
            name='video_files',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
