# Generated by Django 4.2.2 on 2023-06-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_profile_profileimage_alter_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(blank=True, default='https://static.vecteezy.com/system/resources/previews/005/544/718/original/profile-icon-design-free-vector.jpg', null=True, upload_to='static/profile/Images/'),
        ),
    ]
