# Generated by Django 4.2.2 on 2023-06-30 00:41

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_profile_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(blank=True, default='profile-icon-design-free-vector.jpg', null=True, upload_to='static/profile/Images/', validators=[project.models.validate_image_file]),
        ),
    ]
