# Generated by Django 4.2.2 on 2023-07-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_pythoncourse_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythoncourse',
            name='price',
            field=models.IntegerField(blank='false', default=1),
        ),
    ]
