# Generated by Django 4.2.2 on 2023-07-01 19:32

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_teacher_alter_pythoncourse_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profileImage',
            field=models.ImageField(blank=True, default='profile-icon-design-free-vector.jpg', null=True, upload_to='static/Teacher/Images/', validators=[project.models.validate_image_file]),
        ),
    ]
