# Generated by Django 4.2.2 on 2023-07-01 19:37

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_teacher_description_teacher_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profileImage',
            field=models.ImageField(blank=True, default='static/Teacher/Images/profile-icon-design-free-vector.jpg', null=True, upload_to='static/Teacher/Images/', validators=[project.models.validate_image_file]),
        ),
    ]
