# Generated by Django 4.2.2 on 2023-07-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_teacher_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
